version: "3"

services:
  backend:
    image: hiwon/backend
    container_name: backend
    hostname: backend
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    expose:
      - "8080"

  nginx:
    image: hiwon/nginx
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"