spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  # ... spring 설정 ...

  # JWT 설정을 위한 섹션 추가
  security:
    oauth2:
      client:
        registration:
          kakao: # 'kakao'라는 이름으로 클라이언트 등록
            client-id: ${KAKAO_CLIENT_ID} # 카카오 REST API 키
            client-secret: ${KAKAO_CLIENT_SECRET} # 클라이언트 시크릿 (보안 강화 시 사용)
            redirect-uri: ${KAKAO_REDIRECT_URI} # 카카오에 등록한 Redirect URI
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET_KEY}

server:
  url: ${SERVER_LOCAL_URL}