spring:
# H2 ?????? ??
h2:
  console:
    enabled: true # ? ?????? H2 ??? ??? ? ?? ?????.
    path: /h2-console
# ?????? ?? ??
datasource:
  url: jdbc:h2:mem:pigmintdb # ??? ??? ??, DB ??? pigmintdb
  username: sa
  password:
  driver-class-name: org.h2.Driver
# JPA (Java Persistence API) ??
jpa:
  hibernate:
    ddl-auto: create # ?????? ?? ??? ???? '?? ??'???. (?? ???? ???)
  properties:
    hibernate:
      format_sql: true # JPA? ???? SQL ??? ??? ???? ?????.
  defer-datasource-initialization: true # ????? ???? ???? data.sql? ?? ???? ???.

logging:
  level:
    org.hibernate.SQL: debug # SQL ??? ??? ??? ?????.